version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Gtest
          command: 'sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib'
      - run:
          name: Install Git
          command: ' sudo apt update && sudo apt install -y git'
      - run:
          name: Install Gcovr
          command: 'sudo apt-get install -y gcovr'
      - run:
          name: Install Cppcheck and Valgrind
          command: 'sudo apt-get install -y cppcheck && sudo apt install -y valgrind'
      - run:
          name: Creating Build Files
          command: 'cd Task1 && cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cd Task1 && cmake --build build'
      - run:
          name: Run GTest
          command: 'cd Task1/build && ./runTests'
      - run:
          name: Run Cppcheck
          command: 'cd Task1 && cppcheck -j4  --inconclusive --enable=all --language=c++  MyTask.cpp MyTask.h main.cpp'
      - run:
          name: Run Valgrind
          command: 'cd Task1/build && valgrind --tool=memcheck -v --leak-check=yes ./runTests'
      - run:
          name: Run Gcover
          command: 'cd Task1/ && mkdir Build && cd Build && cmake .. && make && make test && make ExperimentalCoverage && gcovr -r ../ && gcovr -r ../ --html -o cover-html.html'
