version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Gtest
          command: 'sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib'
      - run:
          name: Install Git
          command: ' sudo apt update && sudo apt install -y git'
      - run:
          name: Install Gcovr
          command: 'sudo apt-get install -y gcovr'
      - run:
          name: Install Cppcheck and Valgrind
          command: 'sudo apt-get install -y cppcheck && sudo apt install -y valgrind'
      - run:
          name: Creating Build Files
          command: 'cd Task2 && cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cd Task2 && cmake --build build'
      - run:
          name: Run GTest
          command: 'cd Task2/build && ./runTests'
      - run:
          name: Run Cppcheck
          command: 'cd Task2 &&  cppcheck -j4  --inconclusive --enable=all --language=c++  test/* test_gtest.cpp && cppcheck -j4  --inconclusive --enable=all --language=c parallel_algorithm/* naive_algorithm/* parallel_main.cpp naive_main.cpp struct.h'
      - run:
          name: Run Valgrind
          command: 'cd Task2/build && valgrind --tool=memcheck -v --leak-check=yes ./runTests'
      - run:
          name: Run Gcover
          command: 'cd Task2/ && mkdir Build && cd Build && cmake .. && make && make test && make ExperimentalCoverage && gcovr -r ../ ../naive_algorithm/ ../parallel_algorithm/ && gcovr -r ../ ../naive_algorithm/ ../parallel_algorithm/ --html -o cover-html.html'
      - store_artifacts:
          path: ./cover-html.html
          destination: artifact-file
